apiVersion: v1
kind: Secret
metadata:
  name: rabbitmqhost
data:
  rabbitmqhostkey: YW1xcDovL3VzZXI6UEFTU1dPUkRAcmFiYml0bXEuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1Njcy #base64 encoded per secret spec
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer
  namespace: default
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  # labels:
  #   deploymentName: rabbitmq-consumer
spec:
  scaleType: job
  pollingInterval: 5   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  maxReplicaCount: 30  # Optional. Default: 100
  jobTargetRef:
    # parallelism: 1
    # completions: 1
    activeDeadlineSeconds: 3600
    template:
      spec:
        containers:
        - name: rabbitmq-consumer
          image: venkateshsrini3/receivejob
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: rabbitmqhost
          args:
          - 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672'
        restartPolicy: Never  
  triggers:
  - type: rabbitmq
    metadata:
      queueName: hello
      host: rabbitmqhostkey
      queueLength  : '5'
